"""Finish the frozen two-stage experiment from its freshly generated stage-1 files.

For independent submission, run q3_fusion_submit.py; it regenerates stage 1
inside the same invocation. This file only lets a long experiment resume.
"""
import argparse
import csv
import gzip
import hashlib
import json
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path


def job(task):
    project, roots, output, index, cores, resume = task
    from q3_fusion_submit import refine
    name = f"case_{index:03d}"
    folder = output / name / f"n{cores}"
    folder.mkdir(parents=True, exist_ok=True)
    if resume and (folder / "run.json").exists() and (folder / "plan.json").exists():
        report = json.loads((folder / "run.json").read_text(encoding="utf-8"))
        if report.get("schema") == "q3-cold-fusion-v2":
            return dict(case=name, cores=cores, stage1_cycles=report["stage1_cycles"],
                        final_cycles=report["final_cycles"],
                        branch_called=report["branch_search"] is not None,
                        feedback_calls=len(report["feedback_evaluations"]), status="ok",
                        reused_checkpoint=True)
    source = next((root / name / f"n{cores}" for root in roots
                   if (root / name / f"n{cores}" / "run.json").exists()), None)
    if source is None:
        raise FileNotFoundError(f"{name}/n{cores}: no completed stage 1")
    graph = json.loads((project / "official" / "data" / f"{name}.json").read_text(encoding="utf-8"))
    stage1 = json.loads((source / "run.json").read_text(encoding="utf-8"))
    assert stage1["schema"] == "q3-cold-fusion-v1" and stage1["cores"] == cores
    assert stage1["graph_sha256"] == hashlib.sha256(json.dumps(
        graph, sort_keys=True).encode()).hexdigest()
    plan = json.loads((source / f"{name}_multicore_res.json").read_text(encoding="utf-8"))
    with gzip.open(source / "official_result.json.gz", "rt", encoding="utf-8") as stream:
        result = json.load(stream)
    chosen, l2, no_l2, report = refine(
        graph, cores, project / "official" / "data" / "config.txt",
        plan, result, folder)
    report["greedy_report"] = stage1
    report["experimental_resume"] = "stage 1 generated by this frozen experiment"
    (folder / "plan.json").write_text(json.dumps(chosen, separators=(",", ":")) + "\n",
                                      encoding="utf-8")
    with gzip.open(folder / "result.json.gz", "wt", encoding="utf-8", compresslevel=1) as stream:
        json.dump(l2, stream, separators=(",", ":"))
    with gzip.open(folder / "no_l2_same_plan.json.gz", "wt", encoding="utf-8", compresslevel=1) as stream:
        json.dump(no_l2, stream, separators=(",", ":"))
    (folder / "run.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n",
                                     encoding="utf-8")
    return dict(case=name, cores=cores, stage1_cycles=report["stage1_cycles"],
                final_cycles=report["final_cycles"],
                branch_called=report["branch_search"] is not None,
                feedback_calls=len(report["feedback_evaluations"]), status="ok",
                reused_checkpoint=False)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, required=True)
    parser.add_argument("--stage1-roots", type=Path, nargs="+", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--cases", type=int, nargs="+", default=list(range(1, 101)))
    parser.add_argument("--cores", type=int, nargs="+", default=[1, 2, 3, 4, 5])
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--resume", action="store_true")
    a = parser.parse_args()
    project, output = a.project.resolve(), a.output.resolve()
    roots = [r.resolve() for r in a.stage1_roots]
    output.mkdir(parents=True, exist_ok=True)
    jobs = [(project, roots, output, case, cores, a.resume)
            for case in a.cases for cores in a.cores]
    rows = []
    with ProcessPoolExecutor(max_workers=a.workers) as pool:
        futures = [pool.submit(job, item) for item in jobs]
        for future in as_completed(futures):
            row = future.result()
            rows.append(row)
            with (output / "progress.csv").open("w", newline="", encoding="utf-8") as stream:
                writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
                writer.writeheader()
                writer.writerows(sorted(rows, key=lambda r: (r["case"], r["cores"])))
            if not row["reused_checkpoint"]:
                print(row["case"], row["cores"], row["stage1_cycles"],
                      row["final_cycles"], row["branch_called"], flush=True)


if __name__ == "__main__":
    main()
